# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu1304"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://s3-eu-west-1.amazonaws.com/awinvagrantboxes/ubuntu1304.box"

  # Set the host name
  config.vm.host_name = "php-training"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8080 # So you can access apache through http://localhost:8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"

  # Setup memory usage, change the value if you want it to have more
  config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Share a folder to the vm. Useful for sharing code from the host
  # note: for Windows users that you need to add double slash in the path
  # e.g. "C:\\Users\\fred\\php-code"
  #config.vm.synced_folder "YOUR PHP CODE PATH", "/vagrant_data" #, type: "nfs"

  config.vm.provision :chef_solo do |chef|
      ## Chef paths
      # chef.nfs = true
      chef.cookbooks_path = "../../chef-repo/cookbooks"
      chef.roles_path = "../../chef-repo/roles"
      chef.data_bags_path = "../../chef-repo/data_bags"

      # Box Recipes
      chef.add_recipe "apt"
      chef.add_recipe "git"
      chef.add_recipe "php_site_dev"
  end
end
